### ISSUE TITLE
Powergrid frequency is inaccurate

### ISSUE THREAD

**Issue by ertex** [ETAChalmers/infosoffa2-slides#1]
The frequency is not from a Swedish source but from a Norwegian company. 
[    F=$(curl -s -X GET --header 'Accept: application/json' 'https://driftsdata.statnett.no/RestApi/Frequency/BySecond' \](https://github.com/ETAChalmers/infosoffa2-slides/blob/226bf3e594a3b900bb98a6f8636722917f702eaf/images/frekvens.bash#L12)

**Comment by mateuszdrwal** [comment]
Sweden and Norway are on the same grid, and thus have roughly the same frequency. Additionally, SVK uses Norways data on their own site (https://www.svk.se/kontrollrummet). Closing as wontfix, reopen if you find a reliable swedish frequency source.
