### ISSUE TITLE
better lolcat doesn't cooperate with ansi codes

### ISSUE THREAD

**Issue by mateuszdrwal** [ETAChalmers/infosoffa2-slides#4]
the ansi codes some slides use for refreshing only part of the screen break when piped through lolcat, so the text is most often just printed sequentially like if there were no ansi codes

**Comment by xeniagda** [comment]
cope

**Comment by xeniagda** [comment]
fixed in b231ba702d674eef6f13c281abee44319e4fd5db...dcdd82e4497f8af7c9423efcbb0155d4f22310e4
